downgrade decamelize to v5
badges/shields pull request #7449
Opened 2022-01-05 21:14 UTC by chris48s

Might fix https://github.com/badges/shields/issues/7447
Also might fix https://github.com/badges/shields/issues/7324
but I don't know yet

2022-01-05 23:27 UTC, calebcartwright submitted a review, later dismissed
Sounds like this may not address some specific issues, but given the linked upstream issue it seems like we may want to downgrade this regardless so providing an approval accordingly

2022-01-06 16:31 UTC, LitoMore requested changes

2022-01-06 16:31 UTC, LitoMore commented on package.json
> +    "decamelize": "^5.0.1",
You should pin it at [version 3](https://github.com/sindresorhus/decamelize/releases/tag/v4.0.0). The `humanize-string` needs to upgraded as well.

```diff
# dependencies
-    "decamelize": "^6.0.0",
+    "decamelinze": "3.2.0",

# devDependencies
- "humanize-string": "^3.0.0",
+ "humanize-string": "2.0.0",
```

2022-01-06 19:33 UTC, LitoMore commented
The title of the PR needs to be updated.

2022-01-06 19:47 UTC, LitoMore requested changes
Let's remove the `^` mark to make sure dependabot will not update these dependencies by accident.

And please run `npm ci` after these suggestions are applied to ensure that the lockfile is up to date.

2022-01-06 20:00 UTC, chris48s commented
Dependabot bumps dependencies even if they're pinned in package.json e.g: https://github.com/badges/shields/pull/7431/files
Assuming we get a confirmation on https://github.com/badges/shields/issues/7447 I'll add entries to https://github.com/badges/shields/blob/4fef1335d238a4f89a778e857d265b43273dd184/.github/dependabot.yml#L11 to tell dependabot to ignore them

2022-01-06 21:53 UTC, calebcartwright approved these changes
:heart:

2022-01-06 23:50 UTC, calebcartwright commented
Let's go ahead and merge+deploy

2022-01-06 23:50 UTC, merged